version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "appsync-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ikyeet87s7dm"
s3_prefix = "appsync-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Prefix=\"appsync\" DBTableName=\"Pets-Table\" CodeS3Bucket=\"appsync-app-appsync-bucket\""
image_repositories = []
